# Generated by Django 4.2 on 2026-01-10 11:08

import admission.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0001_initial'),
        ('transactions', '0001_initial'),
        ('accounting', '0002_initial'),
        ('branches', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalattendanceregister',
            name='batch',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to=admission.models.active_objects,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='masters.batch',
            ),
        ),
        migrations.AddField(
            model_name='historicalattendanceregister',
            name='branch',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to=admission.models.active_objects,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='branches.branch',
            ),
        ),
        migrations.AddField(
            model_name='historicalattendanceregister',
            name='course',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='masters.course',
            ),
        ),
        migrations.AddField(
            model_name='historicalattendanceregister',
            name='creator',
            field=models.ForeignKey(
                blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicalattendanceregister',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='creator',
            field=models.ForeignKey(
                blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='register',
            field=models.ForeignKey(
                blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admission.attendanceregister'
            ),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='student',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='admission.admission',
            ),
        ),
        migrations.AddField(
            model_name='historicaladmissionenquiry',
            name='branch',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to=admission.models.active_objects,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='branches.branch',
            ),
        ),
        migrations.AddField(
            model_name='historicaladmissionenquiry',
            name='course',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='masters.course',
            ),
        ),
        migrations.AddField(
            model_name='historicaladmissionenquiry',
            name='creator',
            field=models.ForeignKey(
                blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicaladmissionenquiry',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaladmissionenquiry',
            name='tele_caller',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='historicaladmission',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='historicaladmission',
            name='batch',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='masters.batch',
            ),
        ),
        migrations.AddField(
            model_name='historicaladmission',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='historicaladmission',
            name='care_of',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='historicaladmission',
            name='course',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='masters.course',
            ),
        ),
        migrations.AddField(
            model_name='historicaladmission',
            name='creator',
            field=models.ForeignKey(
                blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicaladmission',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaladmission',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='creator',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(model_name='feestructure', name='student', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.admission')),
        migrations.AddField(
            model_name='feestructure',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structure', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='creator',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='admission.admission'),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='batch',
            field=models.ForeignKey(limit_choices_to=admission.models.active_objects, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.batch'),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='branch',
            field=models.ForeignKey(limit_choices_to=admission.models.active_objects, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='course',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.course'),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='creator',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='attendance',
            name='creator',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(model_name='attendance', name='register', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.attendanceregister')),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='admission.admission'),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='branch',
            field=models.ForeignKey(blank=True, limit_choices_to=admission.models.active_objects, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='course',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.course'),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='creator',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='admissionenquiry', name='tele_caller', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')
        ),
        migrations.AddField(
            model_name='admission', name='account', field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.account')
        ),
        migrations.AddField(
            model_name='admission',
            name='batch',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.batch'),
        ),
        migrations.AddField(model_name='admission', name='branch', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
        migrations.AddField(
            model_name='admission',
            name='care_of',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='course',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.course'),
        ),
        migrations.AddField(
            model_name='admission',
            name='creator',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='admission',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
