# Generated by Django 4.2 on 2026-01-10 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
        ('accounting', '0002_initial'),
        ('branches', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalemployee',
            name='course',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='masters.course',
            ),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='creator',
            field=models.ForeignKey(
                blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='department',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='employees.department',
            ),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='designation',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='employees.designation',
            ),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='user',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='historicaldesignation',
            name='creator',
            field=models.ForeignKey(
                blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicaldesignation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='creator',
            field=models.ForeignKey(
                blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='department_lead',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='employees.employee',
            ),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaladvancepayrollpayment',
            name='creator',
            field=models.ForeignKey(
                blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicaladvancepayrollpayment',
            name='employee',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='employees.employee',
            ),
        ),
        migrations.AddField(
            model_name='historicaladvancepayrollpayment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaladvancepayrollpayment',
            name='paid_from',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'under__code__in': ['BANK_ACCOUNT', 'CASH_ACCOUNT']},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='accounting.account',
            ),
        ),
        migrations.AddField(
            model_name='historicaladvancepayrollpayment',
            name='payroll',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='employees.payroll',
            ),
        ),
        migrations.AddField(
            model_name='historicaladvancepayrollpayment',
            name='transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='employee', name='account', field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.account')
        ),
        migrations.AddField(model_name='employee', name='branch', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
        migrations.AddField(
            model_name='employee',
            name='course',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.course'),
        ),
        migrations.AddField(
            model_name='employee',
            name='creator',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.designation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(
                limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='designation',
            name='creator',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='department',
            name='creator',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='department',
            name='department_lead',
            field=models.ForeignKey(
                blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_lead', to='employees.employee'
            ),
        ),
        migrations.AddField(
            model_name='advancepayrollpayment',
            name='creator',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='advancepayrollpayment',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='advancepayrollpayment',
            name='paid_from',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'under__code__in': ['BANK_ACCOUNT', 'CASH_ACCOUNT']},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='advance_payroll_payments',
                to='accounting.account',
            ),
        ),
        migrations.AddField(
            model_name='advancepayrollpayment',
            name='payroll',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.payroll'),
        ),
        migrations.AddField(
            model_name='advancepayrollpayment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction'),
        ),
        migrations.AddConstraint(model_name='payroll', constraint=models.UniqueConstraint(fields=('employee', 'payroll_year', 'payroll_month'), name='unique_employee_payroll')),
    ]
