# Generated by Django 4.2 on 2026-01-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('employees', '0005_historicalemployeeleaverequest_employeeleaverequest')]

    operations = [
        migrations.AddField(
            model_name='employeeleaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('emergency', 'Emergency Leave')], default='casual', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalemployeeleaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('emergency', 'Emergency Leave')], default='casual', max_length=50),
        ),
    ]
