# Generated by Django 4.2 on 2026-01-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('employees', '0006_employeeleaverequest_leave_type_and_more')]

    operations = [
        migrations.AlterModelOptions(name='payroll', options={'ordering': ('-payroll_year', '-payroll_month'), 'verbose_name': 'Payroll', 'verbose_name_plural': 'Payrolls'}),
        migrations.AddField(
            model_name='historicalpayroll',
            name='paid_leaves',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Number of leaves allowed as paid (Default is 1)', max_digits=5),
        ),
        migrations.AddField(
            model_name='historicalpayroll',
            name='total_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Total approved leaves taken this month', max_digits=5),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_leaves',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Number of leaves allowed as paid (Default is 1)', max_digits=5),
        ),
        migrations.AddField(
            model_name='payroll', name='total_leaves', field=models.DecimalField(decimal_places=1, default=0.0, help_text='Total approved leaves taken this month', max_digits=5)
        ),
        migrations.AlterField(
            model_name='historicalpayroll',
            name='absences',
            field=models.DecimalField(
                decimal_places=1, default=0.0, help_text='Total days to deduct from salary (Total Leaves - Paid Leaves)', max_digits=30, verbose_name='Unpaid Absences'
            ),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='absences',
            field=models.DecimalField(
                decimal_places=1, default=0.0, help_text='Total days to deduct from salary (Total Leaves - Paid Leaves)', max_digits=30, verbose_name='Unpaid Absences'
            ),
        ),
    ]
