# Generated by Django 4.2 on 2026-01-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('employees', '0007_alter_payroll_options_historicalpayroll_paid_leaves_and_more')]

    operations = [
        migrations.AddField(
            model_name='employeeleaverequest',
            name='half_day_session',
            field=models.CharField(blank=True, choices=[('first_half', 'First Half (Morning)'), ('second_half', 'Second Half (Afternoon)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeleaverequest',
            name='leave_day_type',
            field=models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day')], default='full_day', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalemployeeleaverequest',
            name='half_day_session',
            field=models.CharField(blank=True, choices=[('first_half', 'First Half (Morning)'), ('second_half', 'Second Half (Afternoon)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployeeleaverequest',
            name='leave_day_type',
            field=models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day')], default='full_day', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeleaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalemployeeleaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
