# Generated by Django 4.2 on 2026-01-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('employees', '0009_alter_employeeleaverequest_leave_type_and_more')]

    operations = [
        migrations.RenameField(model_name='employeeleavebalance', old_name='last_updated_date', new_name='last_accrual_month'),
        migrations.RenameField(model_name='employeeleavebalance', old_name='paid_leave_earned', new_name='paid_leave_balance'),
        migrations.RenameField(model_name='employeeleavebalance', old_name='wfh_earned', new_name='wfh_balance'),
        migrations.RenameField(model_name='historicalemployeeleavebalance', old_name='last_updated_date', new_name='last_accrual_month'),
        migrations.RenameField(model_name='historicalemployeeleavebalance', old_name='paid_leave_earned', new_name='paid_leave_balance'),
        migrations.RenameField(model_name='historicalemployeeleavebalance', old_name='wfh_earned', new_name='wfh_balance'),
    ]
