# Generated by Django 4.2 on 2026-01-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('employees', '0010_rename_last_updated_date_employeeleavebalance_last_accrual_month_and_more')]

    operations = [
        migrations.AlterModelOptions(name='employeeleavebalance', options={}),
        migrations.RemoveField(model_name='employeeleavebalance', name='created'),
        migrations.RemoveField(model_name='employeeleavebalance', name='creator'),
        migrations.RemoveField(model_name='employeeleavebalance', name='is_active'),
        migrations.RemoveField(model_name='employeeleavebalance', name='updated'),
        migrations.AddField(model_name='employeeleavebalance', name='paid_carry_forward', field=models.FloatField(default=0.0)),
        migrations.AddField(model_name='employeeleavebalance', name='wfh_carry_forward', field=models.FloatField(default=0.0)),
        migrations.DeleteModel(name='HistoricalEmployeeLeaveBalance'),
    ]
