# Generated by Django 4.2 on 2026-01-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('employees', '0012_alter_employeeleavebalance_options_and_more')]

    operations = [
        migrations.AddField(model_name='employeeleaverequest', name='is_balance_deducted', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='historicalemployeeleaverequest', name='is_balance_deducted', field=models.BooleanField(default=False)),
    ]
