# Generated by Django 4.2 on 2026-01-27 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('employees', '0013_employeeleaverequest_is_balance_deducted_and_more')]

    operations = [
        migrations.AlterField(model_name='employeeleavebalance', name='last_accrual_month', field=models.DateField(default=datetime.date.today)),
        migrations.AlterField(model_name='employeeleavebalance', name='paid_leave_balance', field=models.FloatField(default=1.0)),
        migrations.AlterField(model_name='employeeleavebalance', name='wfh_balance', field=models.FloatField(default=1.0)),
        migrations.AlterField(model_name='historicalemployeeleavebalance', name='last_accrual_month', field=models.DateField(default=datetime.date.today)),
        migrations.AlterField(model_name='historicalemployeeleavebalance', name='paid_leave_balance', field=models.FloatField(default=1.0)),
        migrations.AlterField(model_name='historicalemployeeleavebalance', name='wfh_balance', field=models.FloatField(default=1.0)),
    ]
