# Generated by Django 4.2 on 2026-01-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('employees', '0014_alter_employeeleavebalance_last_accrual_month_and_more')]

    operations = [
        migrations.AlterField(
            model_name='historicalpayroll',
            name='absences',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Excess leaves to deduct from salary', max_digits=5, verbose_name='Unpaid Absences'),
        ),
        migrations.AlterField(
            model_name='historicalpayroll',
            name='paid_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Leaves covered by balance (Carry over + Current Month)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='historicalpayroll',
            name='total_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Total approved leaves taken this month (Paid + Unpaid)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='absences',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Excess leaves to deduct from salary', max_digits=5, verbose_name='Unpaid Absences'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='paid_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Leaves covered by balance (Carry over + Current Month)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Total approved leaves taken this month (Paid + Unpaid)', max_digits=5),
        ),
    ]
