# Generated by Django 4.2 on 2026-01-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('employees', '0015_alter_historicalpayroll_absences_and_more')]

    operations = [
        migrations.AddField(model_name='employee', name='signature', field=models.FileField(blank=True, null=True, upload_to='employees/doc/signature/')),
        migrations.AddField(model_name='historicalemployee', name='signature', field=models.TextField(blank=True, max_length=100, null=True)),
    ]
