# Generated by Django 4.2 on 2026-01-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('employees', '0016_employee_signature_historicalemployee_signature')]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload a transparent signature image (PNG recommended)', null=True, upload_to='employees/doc/signature/'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='signature',
            field=models.TextField(blank=True, help_text='Upload a transparent signature image (PNG recommended)', max_length=100, null=True),
        ),
    ]
