# Generated by Django 4.2 on 2026-01-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('employees', '0017_alter_employee_signature_and_more')]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage (Per Admission)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage (Per Admission)', max_digits=5, null=True),
        ),
    ]
