# Generated by Django 4.2 on 2026-01-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('employees', '0018_employee_commission_percentage_and_more')]

    operations = [
        migrations.AddField(model_name='employee', name='appointment_letter_sent_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='historicalemployee', name='appointment_letter_sent_at', field=models.DateTimeField(blank=True, null=True)),
    ]
