# Generated by Django 4.2 on 2026-01-31 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('employees', '0020_historicalemployeeattendanceregister_and_more')]

    operations = [migrations.AlterUniqueTogether(name='employeeattendanceregister', unique_together={('employee', 'date')})]
