# Generated by Django 4.2 on 2026-01-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('employees', '0021_alter_employeeattendanceregister_unique_together')]

    operations = [
        migrations.AlterField(model_name='employeeattendanceregister', name='date', field=models.DateField()),
        migrations.AlterField(model_name='historicalemployeeattendanceregister', name='date', field=models.DateField()),
    ]
