# Generated by Django 4.2 on 2026-01-10 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'
                    ),
                ),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                (
                    'is_active',
                    models.BooleanField(
                        default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'
                    ),
                ),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                (
                    'usertype',
                    models.CharField(
                        choices=[
                            ('admin_staff', 'Admin Staff'),
                            ('branch_staff', 'Branch Staff'),
                            ('teacher', 'Teacher'),
                            ('mentor', 'Mentor'),
                            ('sales_head', 'Sales Head'),
                            ('tele_caller', 'Tele Caller'),
                            ('student', 'Student'),
                            ('ceo', 'CEO'),
                            ('cfo', 'CFO'),
                            ('coo', 'COO'),
                            ('hr', 'HR'),
                            ('cmo', 'CMO'),
                            ('partner', 'Partner'),
                        ],
                        max_length=30,
                        verbose_name='Permissions',
                    ),
                ),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
            options={'verbose_name': 'user', 'verbose_name_plural': 'users', 'abstract': False},
        )
    ]
