# Generated by Django 4.2 on 2026-01-21 06:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_tax_state_historicaltax_historicalstate_and_more'),
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0003_alter_account_locking_account_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIncomeExpenseItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Mark as Active')),
                ('particular', models.CharField(max_length=128)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    'discount_percentage',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical income expense item',
                'verbose_name_plural': 'historical income expense items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='IncomeExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Mark as Active')),
                ('particular', models.CharField(max_length=128)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    'discount_percentage',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={'ordering': ['-created'], 'abstract': False},
        ),
        migrations.AlterModelOptions(
            name='historicalincomeexpense',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical income expense',
                'verbose_name_plural': 'historical income expenses',
            },
        ),
        migrations.AlterModelOptions(
            name='incomeexpense',
            options={
                'ordering': ['-created'],
                'permissions': [
                    ('view_income', 'Can view income'),
                    ('add_income', 'Can add income'),
                    ('change_income', 'Can update income'),
                    ('delete_income', 'Can delete income'),
                ],
            },
        ),
        migrations.RemoveIndex(model_name='incomeexpense', name='transaction_type_870fc0_idx'),
        migrations.RemoveIndex(model_name='incomeexpense', name='transaction_party_i_86d484_idx'),
        migrations.RemoveIndex(model_name='incomeexpense', name='transaction_categor_0fda87_idx'),
        migrations.RemoveIndex(model_name='incomeexpense', name='transaction_branch__f76222_idx'),
        migrations.RemoveField(model_name='historicalincomeexpense', name='amount'),
        migrations.RemoveField(model_name='historicalincomeexpense', name='attachment'),
        migrations.RemoveField(model_name='historicalincomeexpense', name='date'),
        migrations.RemoveField(model_name='historicalincomeexpense', name='description'),
        migrations.RemoveField(model_name='historicalincomeexpense', name='id'),
        migrations.RemoveField(model_name='historicalincomeexpense', name='payment_method'),
        migrations.RemoveField(model_name='historicalincomeexpense', name='reference_number'),
        migrations.RemoveField(model_name='historicalincomeexpense', name='type'),
        migrations.RemoveField(model_name='incomeexpense', name='amount'),
        migrations.RemoveField(model_name='incomeexpense', name='attachment'),
        migrations.RemoveField(model_name='incomeexpense', name='date'),
        migrations.RemoveField(model_name='incomeexpense', name='description'),
        migrations.RemoveField(model_name='incomeexpense', name='id'),
        migrations.RemoveField(model_name='incomeexpense', name='payment_method'),
        migrations.RemoveField(model_name='incomeexpense', name='reference_number'),
        migrations.RemoveField(model_name='incomeexpense', name='type'),
        migrations.AddField(model_name='historicalincomeexpense', name='auto_round_off', field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Round Off')),
        migrations.AddField(
            model_name='historicalincomeexpense',
            name='cgst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='CGST Amount'),
        ),
        migrations.AddField(model_name='historicalincomeexpense', name='discount_amount', field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(
            model_name='historicalincomeexpense',
            name='discount_percentage',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name='historicalincomeexpense',
            name='igst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='IGST Amount'),
        ),
        migrations.AddField(model_name='historicalincomeexpense', name='is_gst', field=models.BooleanField(default=False, verbose_name='Is Party')),
        migrations.AddField(model_name='historicalincomeexpense', name='item_discount_total', field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name='historicalincomeexpense', name='nature_of_supply', field=models.CharField(blank=True, max_length=30, null=True)),
        migrations.AddField(model_name='historicalincomeexpense', name='round_off_amount', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
        migrations.AddField(
            model_name='historicalincomeexpense',
            name='sgst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='SGST Amount'),
        ),
        migrations.AddField(
            model_name='historicalincomeexpense',
            name='state',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.state'),
        ),
        migrations.AddField(model_name='historicalincomeexpense', name='sub_total', field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name='historicalincomeexpense', name='tax_amount', field=models.DecimalField(decimal_places=2, default=0, max_digits=15)),
        migrations.AddField(model_name='historicalincomeexpense', name='taxable_amount', field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name='historicalincomeexpense', name='total_quantity', field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name='incomeexpense', name='auto_round_off', field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Round Off')),
        migrations.AddField(
            model_name='incomeexpense', name='cgst_amount', field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='CGST Amount')
        ),
        migrations.AddField(model_name='incomeexpense', name='discount_amount', field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(
            model_name='incomeexpense',
            name='discount_percentage',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name='incomeexpense', name='igst_amount', field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='IGST Amount')
        ),
        migrations.AddField(model_name='incomeexpense', name='is_gst', field=models.BooleanField(default=False, verbose_name='Is Party')),
        migrations.AddField(model_name='incomeexpense', name='item_discount_total', field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name='incomeexpense', name='nature_of_supply', field=models.CharField(blank=True, max_length=30, null=True)),
        migrations.AddField(model_name='incomeexpense', name='round_off_amount', field=models.DecimalField(decimal_places=2, default=0, max_digits=10)),
        migrations.AddField(
            model_name='incomeexpense', name='sgst_amount', field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='SGST Amount')
        ),
        migrations.AddField(
            model_name='incomeexpense', name='state', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.state')
        ),
        migrations.AddField(model_name='incomeexpense', name='sub_total', field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name='incomeexpense', name='tax_amount', field=models.DecimalField(decimal_places=2, default=0, max_digits=15)),
        migrations.AddField(model_name='incomeexpense', name='taxable_amount', field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name='incomeexpense', name='total_quantity', field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AlterField(
            model_name='historicalincomeexpense',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='historicalincomeexpense',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='historicalincomeexpense', name='is_active', field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Mark as Active')
        ),
        migrations.AlterField(
            model_name='historicalincomeexpense',
            name='party',
            field=models.ForeignKey(
                blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Party A/C'
            ),
        ),
        migrations.AlterField(
            model_name='incomeexpense', name='branch', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch')
        ),
        migrations.AlterField(
            model_name='incomeexpense', name='category', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.account')
        ),
        migrations.AlterField(
            model_name='incomeexpense', name='is_active', field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Mark as Active')
        ),
        migrations.AlterField(
            model_name='incomeexpense',
            name='party',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_expenses', to='accounting.account', verbose_name='Party A/C'
            ),
        ),
        migrations.AlterField(
            model_name='incomeexpense',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='incomeexpenseitem', name='branch', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch')
        ),
        migrations.AddField(
            model_name='incomeexpenseitem',
            name='creator',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(model_name='incomeexpenseitem', name='expense', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.incomeexpense')),
        migrations.AddField(
            model_name='incomeexpenseitem', name='tax', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.tax')
        ),
        migrations.AddField(
            model_name='historicalincomeexpenseitem',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='historicalincomeexpenseitem',
            name='creator',
            field=models.ForeignKey(
                blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicalincomeexpenseitem',
            name='expense',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transactions.incomeexpense'),
        ),
        migrations.AddField(
            model_name='historicalincomeexpenseitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalincomeexpenseitem',
            name='tax',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.tax'),
        ),
    ]
