# Generated by Django 4.2 on 2026-01-10 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('transactions', '0001_initial'), ('accounting', '0001_initial'), ('branches', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='historicalgroupmaster',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='historicalgroupmaster',
            name='creator',
            field=models.ForeignKey(
                blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicalgroupmaster',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgroupmaster',
            name='parent',
            field=mptt.fields.TreeForeignKey(
                blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.groupmaster'
            ),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='creator',
            field=models.ForeignKey(
                blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='opening_transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='under',
            field=mptt.fields.TreeForeignKey(
                blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.groupmaster'
            ),
        ),
        migrations.AddField(model_name='groupmaster', name='branch', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
        migrations.AddField(
            model_name='groupmaster',
            name='creator',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='groupmaster',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='accounting.groupmaster'),
        ),
        migrations.AddField(model_name='account', name='branch', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
        migrations.AddField(
            model_name='account',
            name='creator',
            field=models.ForeignKey(
                blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction'),
        ),
        migrations.AddField(model_name='account', name='under', field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.groupmaster')),
        migrations.AlterUniqueTogether(name='groupmaster', unique_together={('branch', 'code')}),
        migrations.AddIndex(model_name='account', index=models.Index(fields=['ledger_type'], name='accounting__ledger__2fb303_idx')),
        migrations.AddIndex(model_name='account', index=models.Index(fields=['branch', 'ledger_type'], name='accounting__branch__14b739_idx')),
        migrations.AddIndex(model_name='account', index=models.Index(fields=['branch', 'under'], name='accounting__branch__fc5931_idx')),
        migrations.AddIndex(model_name='account', index=models.Index(fields=['branch', 'code'], name='accounting__branch__76de4a_idx')),
        migrations.AddIndex(model_name='account', index=models.Index(fields=['is_locked'], name='accounting__is_lock_61645f_idx')),
        migrations.AlterUniqueTogether(name='account', unique_together={('branch', 'code')}),
    ]
